### ISSUE TITLE
Google login is not working with modded APK but there is a solution

### ISSUE THREAD

**Issue by evildog1** [rqn00b/pokego-cert-unpinning#1]
When trying to login with Google account, the game is stuck and the loading just spinning for infinite. It is normal that Google login does not work when the APK is being re-signed because the signature is different. However, i have replaced the original signature in your modded APK and leave it unsigned to the game can login with Google account. Root and Lucky Patcher is required to disable signature check and install unsigned APK.

Unsigned APK is not required for peoples who use Pokemon Trainer Club account

How to disable signature check: https://www.alphagamers.net/threads/how-to-install-an-unsigned-apk-root-lucky-patcher.20998/

Unsigned APK for rooted devices: http://usersdownload.com/n8zwmkri3ipi.html

**Comment by rqn00b** [comment]
The other solution would be to read the README.md and see that the script.py is required for google login to work with this. 
I made this specifically so people wouldn't have to root their devices to mitm their connection (which is the only thing that cert pinning blocks)
I'm working on a fix for logging in with google, but for now the best thing to do would be to either get a PTC account or use mitmproxy for intercepting the network traffic.
